FROM ubuntu:22.04 as unit-builder

ARG PHP_VERSION='8.2'
ARG UNIT_VERSION='1.31.1'

ENV DEBIAN_FRONTEND=noninteractive

COPY php/ondrej_ubuntu_php.gpg /etc/apt/trusted.gpg.d/ondrej_ubuntu_php.gpg

# Get essentials for compiling Unit PHP
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gnupg2 ca-certificates curl zip unzip \
    && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-jammy.list \
    && apt-get update \
    && apt-get -y --no-install-recommends install php${PHP_VERSION}-embed php${PHP_VERSION}-dev php${PHP_VERSION}-cli

# Build PHP module for Nginx Unit
RUN curl -O https://unit.nginx.org/download/unit-${UNIT_VERSION}.tar.gz \
    && tar xzf unit-$UNIT_VERSION.tar.gz \
    && cd unit-$UNIT_VERSION \
    && ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/control.unit.sock \
        --pid=/var/run/unit.pid --log=/var/log/unit.log --tmp=/var/tmp --user=unit --group=unit \
        --tests --modules=/usr/lib/unit/modules --libdir=/usr/lib/x86_64-linux-gnu \
    && ./configure php --module=php --config=php-config${PHP_VERSION} \
    && make php \
    && make install php


FROM ubuntu:22.04

ARG PHP_VERSION='8.2'

LABEL maintainer="Chris Fidao (fideloper@fly.io)"

ENV DEBIAN_FRONTEND=noninteractive \
    COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/composer \
    COMPOSER_MAX_PARALLEL_HTTP=24 \
    PHP_PM_MAX_CHILDREN=10 \
    PHP_PM_START_SERVERS=3 \
    PHP_MIN_SPARE_SERVERS=2 \
    PHP_MAX_SPARE_SERVERS=4 \
    PHP_DATE_TIMEZONE=UTC \
    PHP_DISPLAY_ERRORS=Off \
    PHP_ERROR_REPORTING=22527 \
    PHP_MEMORY_LIMIT=256M \
    PHP_MAX_EXECUTION_TIME=90 \
    PHP_POST_MAX_SIZE=100M \
    PHP_UPLOAD_MAX_FILE_SIZE=100M \ 
    PHP_ALLOW_URL_FOPEN=1

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY php/ondrej_ubuntu_php.gpg /etc/apt/trusted.gpg.d/ondrej_ubuntu_php.gpg
ADD php/packages/${PHP_VERSION}.txt /tmp/php-packages.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends gnupg2 ca-certificates git-core curl zip unzip \
                                                  rsync vim-tiny htop sqlite3 cron \
    && ln -sf /usr/bin/vim.tiny /etc/alternatives/vim \
    && ln -sf /etc/alternatives/vim /usr/bin/vim \
    && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-jammy.list \
    && apt-get update \
    && apt-get -y --no-install-recommends install php${PHP_VERSION}-embed $(cat /tmp/php-packages.txt) \
    && mkdir -p /var/www/html/public && echo "<?php phpinfo();" > /var/www/html/public/index.php \
    && curl --output /usr/share/keyrings/nginx-keyring.gpg https://unit.nginx.org/keys/nginx-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ jammy unit\ndeb-src [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ jammy unit" > /etc/apt/sources.list.d/unit.list \
    && apt-get update \
    && apt-get install -y unit \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* \
    && chown -R unit:unit /var/www/html

COPY --from=unit-builder /usr/lib/unit/modules/php.unit.so /usr/lib/unit/modules/php.unit.so
COPY unit/conf.json /var/lib/unit/conf.json
COPY entrypoint-unit.sh /entrypoint

WORKDIR /var/www/html

ENTRYPOINT ["/entrypoint"]
